// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://pzxbypzxholtqfsdiysc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6eGJ5cHp4aG9sdHFmc2RpeXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzE5MzAsImV4cCI6MjA2MDgwNzkzMH0.1WJO4xv7AbLHRJCsg67LocldCd7HLF7e7BG69z4S_Pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
